version: '{build}'
image: Visual Studio 2015

configuration:
  - Debug
  - Release

install:
  - git submodule update --init --recursive . ":(exclude)lib/boost"

before_build:
  - mkdir build && cd build
  - cmake .. -G "Visual Studio 14 2015" -DCPACK_OUTPUT_FILE_PREFIX=.. -DCPACK_OUTPUT_FILE_POSTFIX=%CONFIGURATION% -DBOOST_ROOT="C:\Libraries\boost_1_65_1" -DEIGEN3_INCLUDE_DIR="%APPVEYOR_BUILD_FOLDER%\lib\eigen"

build_script:
  - cmake --build . --config %CONFIGURATION% --target streamer_unity
  - cmake --build . --config %CONFIGURATION% --target package

artifacts:
  - path: streamer-*-win32-*.zip
    name: Streamer Plugin

deploy:
  - provider: BinTray
    username: incognito
    api_key:
      secure: e0xOM0EZQFdpPDMOnEH6Zi8QD8YMMnSflcXFODRfwE/dHpWyNf25yNrSMR6gKjAT
    subject: incognito
    repo: streamer-plugin
    package: builds
    version: latest
    publish: true
    override: true
